### ISSUE TITLE
Icon size at checkout sizing is too big

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/grandnode#3]
<img width="769" alt="Screenshot 2024-02-25 at 17 13 12" src="https://github.com/btcpayserver/grandnode/assets/36959754/fb238983-a840-458e-bcf8-798b37b00fc2">

**Comment by little-fish-foundation** [comment]
> <img alt="Screenshot 2024-02-25 at 17 13 12" width="769" src="https://private-user-images.githubusercontent.com/36959754/307589663-fb238983-a840-458e-bcf8-798b37b00fc2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI5NjM3NjIsIm5iZiI6MTc2Mjk2MzQ2MiwicGF0aCI6Ii8zNjk1OTc1NC8zMDc1ODk2NjMtZmIyMzg5ODMtYTg0MC00NThlLWJjZjgtNzk4YjM3YjAwZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTEyVDE2MDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZWRlMjRiNDgwODBiZGMzYzFmMTE1ZWE0MWUwZmE3NWM1YmU4YzhjOTRlNDgzOGE5NWEwMDFkYWY1YzNhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1_oqYFDIWuQYplcxPoWP4DvlGeegs0xGsb9QbNbgnGc">

why you have the paypal pay?

**Comment by little-fish-foundation** [comment]
> > <img alt="截图 2024-02-25 at 17 13 12" width="769" src="https://private-user-images.githubusercontent.com/36959754/307589663-fb238983-a840-458e-bcf8-798b37b00fc2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI5NjM3NjIsIm5iZiI6MTc2Mjk2MzQ2MiwicGF0aCI6Ii8zNjk1OTc1NC8zMDc1ODk2NjMtZmIyMzg5ODMtYTg0MC00NThlLWJjZjgtNzk4YjM3YjAwZmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTEyVDE2MDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZWRlMjRiNDgwODBiZGMzYzFmMTE1ZWE0MWUwZmE3NWM1YmU4YzhjOTRlNDgzOGE5NWEwMDFkYWY1YzNhM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1_oqYFDIWuQYplcxPoWP4DvlGeegs0xGsb9QbNbgnGc">
> 
> 为什么你有 PayPal Pay？

i only have the some  pay

<img width="1765" height="639" alt="Image" src="https://github.com/user-attachments/assets/feb525d1-be50-4c96-9258-270c52459159" />

**Comment by Nisaba** [comment]
Please check your BTCPay plugin settings to see if all it's OK...
